version: '3'

services:
  grafana:
    image: grafana/grafana-oss:8.4.4
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - graph_network
    env_file:
      - ./grafana/grafana.env
    restart: always

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: 'prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - graph_network
    restart: always

  unpoller:
    image: golift/unifi-poller:latest
    container_name: 'unpoller'
    ports:
      - '9130:9130'
    volumes:
      - ./unpoller:/config
    networks:
      - graph_network
    depends_on:
      - grafana
      - prometheus
    environment:
     - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
     - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
     - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASSWORD}
    restart: unless-stopped

volumes:
  grafana_data: {}
  prometheus_data: {}

networks:
  graph_network:
