global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'unpoller'
    static_configs:
      - targets: ['unpoller:9130']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
